### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-faoclh#27]
Provide a mechanism to track the activities on the CKAN catalog in Google Analytics.

Related to the analisis doc provided by GeoSolutions to FAO-CIO:
https://docs.google.com/document/d/114gEYAjK3kS9TAq54XYl8n1mskucSOTtBncStrgRaqo/edit?usp=sharing

The task here is related to the two reported issues (development / review / testing):
https://github.com/ckan/ckanext-googleanalytics/issues/38
https://github.com/ckan/ckanext-googleanalytics/issues/39

First of all we should verify if the issues above still exist in ckanext-googleanalytics (we can also check if updated solutions to use google analytics in CKAN exist today).
Then we need to provide an installation on [GeoSolutions DEV server](http://faoclh.geo-solutions.it/) using a GeoSolutions Google account for test and for the setup of the analytics part Google side.

The basic inatallation and configuration procedure must be properly documented inside a dedicated section of the [README file ](https://github.com/geosolutions-it/ckanext-faoclh/blob/master/README.md).

**Comment by abulojoshua1** [comment]
@etj, @tdipisa, issues ([#38](https://github.com/ckan/ckanext-googleanalytics/issues/38) and [#39](https://github.com/ckan/ckanext-googleanalytics/issues/39) of the extension) still exist in ckanext-googleanalytics. This is because ckanext-googleanalytics uses client-side javascript to provide analytics data which does not exits for the case of downloads and api calls. Should I go ahead and document installation steps for ckanext-googleanalytics with  it's issues still open?
